version: '3.1'

services:

  db:
    container_name: pgsql
    image: postgres:alpine
    restart: always
    ports:
     - 15432:5432
    volumes:
      - oldpaper_db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: oldpaper
      POSTGRES_USER: oldpaper
      POSTGRES_PASSWORD: password

volumes:
    oldpaper_db:
      external: false
