version: '3.1'

services:

  app:
    container_name: oldpaper
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=oldpaper://oldpaper:oldpaper@127.0.0.1:15432
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: pgsql
    image: docker.io/postgres:alpine
    restart: always
    ports:
     - 15432:5432
    volumes:
      - oldpaper_db:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=oldpaper
      - POSTGRES_USER=oldpaper
      - POSTGRES_PASSWORD=oldpaper
    healthcheck:
      test: ["CMD", "pg_isready -u oldpaper oldpaper"]
      interval: 5s
      timeout: 60s
      retries: 10
      start_period: 10s

volumes:
    oldpaper_db:
      external: false
